v = input('Digite algo: ')
print('O tipo primitivo do valor é', type(v))
print('Só tem espaços?', v.isspace())
print('É um numérico? ', v.isnumeric())
print('É alfabético? ',v.isalpha())
print('É alfanumérico? ', v.isalnum())
print('Está em maiuscúlo? ', v.isupper())
print('Está em minúsculo? ', v.islower())
print('Está capitalizada? ', v.istitle())
